export enum ServiceCategory {
  REPAIR_COMPUTERS = 'REPAIR_COMPUTERS',
  REPAIR_MOBILES = 'REPAIR_MOBILES',
  REMOTE_SUPPORT = 'REMOTE_SUPPORT',
  INSTALLATION = 'INSTALLATION',
  MAINTENANCE = 'MAINTENANCE',
  CONSULTATION = 'CONSULTATION',
}