name: fixi_mobile
description: Marketplace de Servicios Técnicos Fixi

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3

  # Navigation
  go_router: ^12.1.3

  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  material_design_icons_flutter: ^1.1.8
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

  # Maps & Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Image & Camera
  image_picker: ^1.0.4
  image_cropper: ^5.0.0

  # Real-time Communication
  socket_io_client: ^2.0.3+1

  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0

  # Payments (WebViews for external payment gateways)
  flutter_inappwebview: ^6.0.0

  # Biometrics
  local_auth: ^2.1.6

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# App Configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1E3A8A"
  adaptive_icon_foreground: "assets/icons/app_icon_adaptive.png"

flutter_launcher_name: "Fixi"

flutter_native_splash:
  color: "#1E3A8A"
  image: assets/icons/splash_icon.png
  android_gravity: center
  ios_content_mode: center